name: pt.csust_crawler

on:
  workflow_dispatch:
  # schedule:
  # - cron: '30 */3 * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    
    - name: Set env
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run crawler
      run: |
        echo "## 运行时间：" > info.bak.log
        echo `date` >> info.bak.log
        echo "## 运行情况：" >> info.bak.log
        python main.py >> info.bak.log
        echo -e "=========================\n\n" >> info.bak.log
    - name: Update logs
      run: |
        source update_log.sh
    - name: Commit .env #上传新的refresh_token到仓库
      run: |
        git config --global user.email "your_email"
        git config --global user.name "your_nickname"
        git add .
        git commit --amend -m "chore: run success"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true