name: pt.csust_crawler

on:
  workflow_dispatch:
  # schedule:
  # - cron: '30 */3 * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    
    - name: Set env
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run crawler
      run: |
        python main.py
    - name: Commit .env #上传新的refresh_token到仓库
      run: |
        git config --global user.email "your_email"
        git config --global user.name "your_nickname"
        git add .
        git commit --amend -m "chore: run success"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true